### ISSUE TITLE
videointelligence.Feature.PERSON_DETECTION - Wrong number of people detected

### ISSUE THREAD

**Issue by rootto** [googleapis/python-videointelligence#101] opened 2021-01-07 09:28 UTC
Hi,

I'm testing the Detect People API using the example:

https://github.com/googleapis/python-videointelligence/blob/master/samples/analyze/video_detect_faces_gcs_beta.py

with the video: https://www.pexels.com/video/group-of-people-in-a-business-meeting-in-a-conference-room-3202044/

Looking at the output more than 6 people are returned. I can filter out some of the annotations by looking at bounding box overlap. Any ideas if there is a way to get a confidence rating for each annotation ? Both annotation.confidence and track.confidence don't exist and I can't find anything in the documentation.

Thanks 

Nicola 

#### Environment details

  - Linux 5.4.74-10576
  - Python version: 3.7.3
  - pip version: 20.3.1
  - `google-cloud-videointelligence` version: `2.0.0

**Comment by munkhuushmgl** [comment] 2021-01-08 01:27
@rootto I was able to reproduce this error. Looks like it does not return any value for confidence.


I am looking deeper into the issue. will give you update soon.

**Comment by munkhuushmgl** [comment] 2021-01-08 01:27
![image](https://user-images.githubusercontent.com/45373284/103963275-ad5e5f80-510d-11eb-9b41-56069cd93453.png)

**Comment by munkhuushmgl** [comment] 2021-01-08 01:37
As I looked in proto, there is no confidence in video annotation object. https://github.com/googleapis/python-videointelligence/blob/89adad76c5fb998894eeb36eec25454db982cacb/google/cloud/videointelligence_v1p3beta1/types/video_intelligence.py#L751-L763


Confidence exists inside Video.Track object

https://github.com/googleapis/python-videointelligence/blob/89adad76c5fb998894eeb36eec25454db982cacb/google/cloud/videointelligence_v1p3beta1/types/video_intelligence.py#L602-L628

**Comment by munkhuushmgl** [comment] 2021-01-08 01:41
@rootto  Could you be specific on `Any ideas if there is a way to get a confidence rating for each annotation?`

**Comment by rootto** [comment] 2021-01-08 08:27
@munkhuushmgl thanks for looking into this. Indeed  `track.confidence` exist, but in my code I get 0 regardless of the track, which doesn't really help

In my vague question, I was asking if there are other ways within the Video Intelligence library to achieve the same result. I can see the LabelDetectionConfig allows to specify confidence thresholds,  will it be possible to introduce the same for other type of detection types ?  

For now I'm getting good results filtering out annotations which overlap for more than 30% of their area, but it would be great if I can achieve the same directly with the library.

**Comment by munkhuushmgl** [comment] 2021-01-08 17:47
@telpirion Could you answer this for me?

**Comment by telpirion** [comment] 2021-01-12 18:12
I have confirmed that we can't get the confidence values using `track.confidence`. I'm reaching out to the product team for additional input.

**Comment by telpirion** [comment] 2021-03-08 16:52
A fix for this issue has been pushed to production. You should now see confidence levels associated with people detected by the service. Please reopen this issue if you continue to see problems.

**Closed by telpirion** 2021-03-08 16:52 UTC
Labels: api: videointelligence, type: question
